'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Header } from '@/components/Header';
import { supabase } from '@/lib/supabase';

type Contract={id:string;file_path:string;original_filename:string;uploaded_at:string;status:string;signed_at:string|null;signer_name:string|null;opened_at?:string|null};

export default function Contracts(){
  const router=useRouter();const[rows,setRows]=useState<Contract[]>([]);const[msg,setMsg]=useState('');const[signing,setSigning]=useState<Contract|null>(null);const[opened,setOpened]=useState<Set<string>>(new Set());const[saving,setSaving]=useState(false);const[loading,setLoading]=useState(true);
  useEffect(()=>{void load()},[]);
  async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login');return}const{data:e}=await supabase.from('employees').select('id').eq('auth_user_id',user.id).maybeSingle();if(!e){setMsg('Your employee profile is not linked. Please contact HR.');setLoading(false);return}const{data,error}=await supabase.from('employee_contracts').select('*').eq('employee_id',e.id).is('archived_at',null).order('uploaded_at',{ascending:false});if(error)setMsg('Contracts could not be loaded.');setRows(data||[]);setOpened(new Set((data||[]).filter(c=>c.opened_at).map(c=>c.id)));setLoading(false)}
  async function open(c:Contract){setMsg('');const response=await fetch(`/api/contracts/${c.id}`,{cache:'no-store'});const data=await response.json();if(!response.ok||!data.url){setMsg(data.error||'The contract could not be opened.');return}setOpened(current=>new Set(current).add(c.id));window.open(data.url,'_blank','noopener,noreferrer')}
  async function sign(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!signing||saving)return;setSaving(true);setMsg('');const fd=new FormData(event.currentTarget);try{const response=await fetch(`/api/contracts/${signing.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({signerName:fd.get('signerName'),accepted:fd.get('accepted')==='on'})});const data=await response.json();if(!response.ok){setMsg(data.error||'The contract could not be signed.');return}setMsg('Contract signed successfully. It will remain available until HR securely archives the employee pack.');setSigning(null);await load()}catch{setMsg('The contract could not be signed. Please try again.')}finally{setSaving(false)}}
  if(loading)return <main className="shell"><Header/><section className="hero"><h1>Loading contracts...</h1></section></main>;
  return <main className="shell"><Header/><section className="hero"><span className="pill">Contracts</span><h1>My Contracts</h1><p className="muted">Open and review each contract before signing. Signed files remain available until HR securely archives your employee pack.</p></section>{msg&&<section className="section"><div className="card" role="status"><strong>{msg}</strong></div></section>}<section className="section"><div className="grid">{rows.length===0?<div className="card"><p>No active contract files are currently held in your portal.</p></div>:rows.map(c=><div className="card" key={c.id}><span className="pill">{c.status==='signed'?'Signed':'Awaiting signature'}</span><h3>{c.original_filename}</h3><p className="muted">Uploaded {new Date(c.uploaded_at).toLocaleDateString()}</p>{c.signed_at&&<p><strong>Signed:</strong> {new Date(c.signed_at).toLocaleString()} by {c.signer_name}</p>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="button" onClick={()=>open(c)}>Open contract</button>{c.status!=='signed'&&<button className="button secondary" disabled={!opened.has(c.id)} title={opened.has(c.id)?'Sign this contract':'Open the contract first'} onClick={()=>setSigning(c)}>Sign Contract</button>}</div>{c.status!=='signed'&&!opened.has(c.id)&&<p className="muted">Open the contract before the signing button becomes available.</p>}</div>)}</div></section><section className="section"><Link href="/">← Back to My Portal</Link></section>{signing&&<div className="modal-backdrop"><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="sign-title"><h2 id="sign-title">Sign {signing.original_filename}</h2><p className="muted">Your typed name, the exact contract file and signing time will be retained as the signature record.</p><form onSubmit={sign}><label htmlFor="signer-name">Full legal name</label><input id="signer-name" name="signerName" required autoComplete="name"/><label><input type="checkbox" name="accepted" required/> I confirm that I opened, read and agree to this contract.</label><div className="admin-form-actions"><button className="button" disabled={saving}>{saving?'Signing...':'Sign contract'}</button><button className="button secondary" type="button" disabled={saving} onClick={()=>setSigning(null)}>Cancel</button></div></form></section></div>}</main>;
}
