'use client';
import {FormEvent,useEffect,useState} from 'react';import Link from 'next/link';import {useRouter} from 'next/navigation';import {Header} from '@/components/Header';import {supabase} from '@/lib/supabase';
type Employee={id:string;first_name:string|null;last_name:string|null};type Contract={id:string;employee_id:string;original_filename:string;file_path:string;status:string;uploaded_at:string;signed_at:string|null;signer_name:string|null};
export default function ManageContracts(){const router=useRouter();const[employees,setEmployees]=useState<Employee[]>([]);const[rows,setRows]=useState<Contract[]>([]);const[msg,setMsg]=useState('');const[saving,setSaving]=useState(false);const[allowed,setAllowed]=useState(false);
useEffect(()=>{load()},[]);async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login');return}const role=String(user.app_metadata?.role||'staff').toLowerCase();if(!['manager','hr_admin','admin'].includes(role))return;setAllowed(true);const[{data:e},{data:c}]=await Promise.all([supabase.from('employees').select('id,first_name,last_name').order('first_name'),supabase.from('employee_contracts').select('*').order('uploaded_at',{ascending:false})]);setEmployees(e||[]);setRows(c||[])}
async function upload(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setSaving(true);setMsg('');const fd=new FormData(ev.currentTarget),employeeId=String(fd.get('employee_id')||''),file=fd.get('contract') as File;if(!employeeId||!file?.name){setMsg('Select an employee and contract file.');setSaving(false);return}const{data:{user}}=await supabase.auth.getUser();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${employeeId}/${Date.now()}-${safe}`;const{error:uploadError}=await supabase.storage.from('employee-contracts').upload(path,file,{upsert:false});if(uploadError){setMsg(uploadError.message);setSaving(false);return}const{error}=await supabase.from('employee_contracts').insert({employee_id:employeeId,file_path:path,original_filename:file.name,uploaded_by:user?.id,status:'awaiting_signature'});if(error){await supabase.storage.from('employee-contracts').remove([path]);setMsg(error.message);setSaving(false);return}ev.currentTarget.reset();setMsg('Contract uploaded. It is now waiting for the employee to sign.');setSaving(false);await load()}
async function open(c:Contract){const{data,error}=await supabase.storage.from('employee-contracts').createSignedUrl(c.file_path,300);if(error){setMsg(error.message);return}window.open(data.signedUrl,'_blank')}
const employeeName=(id:string)=>{const e=employees.find(x=>x.id===id);return e?`${e.first_name||''} ${e.last_name||''}`.trim():'Employee'};
if(!allowed)return <main className="shell"><Header/><section className="hero"><h1>Contracts</h1><p>This area is for Manager, HR and Admin only.</p><Link href="/">← Back</Link></section></main>;
return <main className="shell"><Header/><section className="hero"><span className="pill">Management</span><h1>Contracts</h1><p className="muted">Upload an individual contract to an employee. The employee opens and signs it from their dashboard.</p></section><section className="section"><div className="card"><h2>Upload Contract</h2><form className="admin-form" onSubmit={upload}><label>Employee<select name="employee_id" required defaultValue=""><option value="" disabled>Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select></label><label>Contract file<input name="contract" type="file" accept=".pdf,.doc,.docx" required/></label><div className="admin-form-actions"><button className="button" disabled={saving}>{saving?'Uploading...':'Upload contract'}</button></div></form>{msg&&<p><strong>{msg}</strong></p>}</div></section><section className="section"><h2>Employee Contracts</h2><div className="grid">{rows.map(c=><div className="card" key={c.id}><span className="pill">{c.status==='signed'?'Signed':'Awaiting signature'}</span><h3>{employeeName(c.employee_id)}</h3><p>{c.original_filename}</p>{c.signed_at&&<p><strong>Signed:</strong> {new Date(c.signed_at).toLocaleString()} by {c.signer_name}</p>}<button className="button" onClick={()=>open(c)}>Open contract</button></div>)}</div></section><section className="section"><Link href="/">← Back to My Portal</Link></section></main>}
