'use client';
import {FormEvent,useEffect,useState} from 'react';import Link from 'next/link';import {Header} from '@/components/Header';
type Employee={id:string;first_name:string|null;last_name:string|null};type Contract={id:string;employee_id:string;original_filename:string;status:string;uploaded_at:string;signed_at:string|null;signer_name:string|null;signed_url?:string|null};
export default function ManageContracts(){const[employees,setEmployees]=useState<Employee[]>([]);const[rows,setRows]=useState<Contract[]>([]);const[msg,setMsg]=useState('');const[saving,setSaving]=useState(false);const[loading,setLoading]=useState(true);const[allowed,setAllowed]=useState(true);
useEffect(()=>{load()},[]);async function load(){setLoading(true);setMsg('');try{const response=await fetch('/api/admin/contracts',{cache:'no-store'});const data=await response.json();if(response.status===401){window.location.href='/login';return}if(!response.ok){setAllowed(false);setMsg(data.error||'Unable to load contracts.');return}setAllowed(true);setEmployees(data.employees||[]);setRows(data.contracts||[])}catch{setAllowed(false);setMsg('Unable to load contracts.')}finally{setLoading(false)}}
async function upload(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setSaving(true);setMsg('');const form=ev.currentTarget;try{const response=await fetch('/api/admin/contracts',{method:'POST',body:new FormData(form)});const data=await response.json();if(!response.ok){setMsg(data.error||'Unable to upload contract.');return}form.reset();setMsg(data.message||'Contract uploaded.');await load()}catch{setMsg('Unable to upload contract.')}finally{setSaving(false)}}
function open(c:Contract){if(!c.signed_url){setMsg('Unable to create a secure link for this contract. Please refresh and try again.');return}window.open(c.signed_url,'_blank')}
const employeeName=(id:string)=>{const e=employees.find(x=>x.id===id);return e?`${e.first_name||''} ${e.last_name||''}`.trim():'Employee'};
if(loading)return <main className="shell"><Header/><section className="hero"><h1>Loading Contracts...</h1></section></main>;
if(!allowed)return <main className="shell"><Header/><section className="hero"><h1>Contracts</h1><p>{msg||'This area is for Manager, HR and Admin only.'}</p><Link href="/">← Back</Link></section></main>;
return <main className="shell"><Header/><section className="hero"><span className="pill">Management</span><h1>Contracts</h1><p className="muted">Upload an individual contract to an employee. The employee opens and signs it from their dashboard.</p></section><section className="section"><div className="card"><h2>Upload Contract</h2><form className="admin-form" onSubmit={upload}><label>Employee<select name="employee_id" required defaultValue=""><option value="" disabled>Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select></label><label>Contract file<input name="contract" type="file" accept=".pdf,.doc,.docx" required/></label><div className="admin-form-actions"><button className="button" disabled={saving}>{saving?'Uploading...':'Upload contract'}</button></div></form>{msg&&<p><strong>{msg}</strong></p>}</div></section><section className="section"><h2>Employee Contracts</h2><div className="grid">{rows.length===0?<div className="card"><p>No contracts uploaded yet.</p></div>:rows.map(c=><div className="card" key={c.id}><span className="pill">{c.status==='signed'?'Signed':'Awaiting signature'}</span><h3>{employeeName(c.employee_id)}</h3><p>{c.original_filename}</p><p className="muted">Uploaded {new Date(c.uploaded_at).toLocaleDateString()}</p>{c.signed_at&&<p><strong>Signed:</strong> {new Date(c.signed_at).toLocaleString()} by {c.signer_name}</p>}<button className="button" onClick={()=>open(c)}>Open contract</button></div>)}</div></section><section className="section"><Link href="/admin">← Back to Admin</Link></section></main>}
