'use client';

import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Header } from '@/components/Header';
import { supabase } from '@/lib/supabase';

type Row={id:string;employee_id:string;leave_type:string;start_date:string;end_date:string;reason:string|null;status:string;manager_comment:string|null;medical_certificate_path:string|null;employees?:{first_name:string|null;last_name:string|null}|null};
type Balance={employee_id:string;first_name:string|null;last_name:string|null;annual_leave_entitlement:number;approved_days:number;pending_days:number;remaining_days:number;sick_leave_entitlement?:number;sick_days_taken?:number;sick_days_remaining?:number};
export default function TeamLeave(){
 const router=useRouter(); const [rows,setRows]=useState<Row[]>([]); const [balances,setBalances]=useState<Balance[]>([]); const [allowed,setAllowed]=useState(false); const [loading,setLoading]=useState(true); const [openingCertificate,setOpeningCertificate]=useState<string|null>(null);
 useEffect(()=>{load()},[]);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login');return;} const role=String(user.app_metadata?.role||'staff').toLowerCase(); if(!['manager','hr','hr_admin','admin','administrator'].includes(role)){setLoading(false);return;} setAllowed(true); const [requestsResult,annualResult,sickResult]=await Promise.all([supabase.from('leave_requests').select('id,employee_id,leave_type,start_date,end_date,reason,status,manager_comment,medical_certificate_path,employees(first_name,last_name)').order('created_at',{ascending:false}),supabase.from('employee_leave_balances').select('employee_id,first_name,last_name,annual_leave_entitlement,approved_days,pending_days,remaining_days').order('first_name'),supabase.from('employee_sick_leave_balances').select('employee_id,sick_leave_entitlement,sick_days_taken,sick_days_remaining')]); if(requestsResult.error){console.error(requestsResult.error);setRows([]);}else setRows((requestsResult.data||[]) as unknown as Row[]); if(annualResult.error){console.error(annualResult.error);setBalances([]);}else{const sickMap=new Map((sickResult.data||[]).map(s=>[s.employee_id,s]));setBalances((annualResult.data||[]).map(a=>({...a,...(sickMap.get(a.employee_id)||{})})) as Balance[]);} setLoading(false);}
 async function decide(id:string,status:'approved'|'declined'){const comment=window.prompt('Manager comment (optional):')||'';const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('leave_requests').update({status,manager_comment:comment,decided_by:user?.id||null,decided_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(error.message);return;}await load();}
 async function viewCertificate(path:string){setOpeningCertificate(path);const {data,error}=await supabase.storage.from('medical-certificates').createSignedUrl(path,60);setOpeningCertificate(null);if(error||!data?.signedUrl){alert(error?.message||'Unable to open the medical certificate.');return;}window.open(data.signedUrl,'_blank','noopener,noreferrer');}
 if(loading)return <main className="shell"><Header/><section className="hero"><h1>Loading team leave...</h1></section></main>;
 if(!allowed)return <main className="shell"><Header/><section className="hero"><h1>Team Leave</h1><p className="muted">This page is only available to Managers, HR and Admin.</p><Link href="/">← Back to My Portal</Link></section></main>;
 return <main className="shell"><Header/><section className="hero"><span className="pill">Manager</span><h1>Team Leave Management</h1><p className="muted">Review leave balances and manage staff leave requests.</p></section>
 <section className="section"><h2>Staff Leave Balances</h2><div style={{overflowX:'auto'}}><table className="admin-table"><thead><tr><th>Employee</th><th>Annual entitlement</th><th>Annual taken</th><th>Annual pending</th><th>Annual remaining</th><th>Sick entitlement</th><th>Sick taken</th><th>Sick remaining</th></tr></thead><tbody>{balances.length===0?<tr><td colSpan={8}>No leave balances available.</td></tr>:balances.map(b=><tr key={b.employee_id}><td><strong>{b.first_name} {b.last_name}</strong></td><td>{b.annual_leave_entitlement??0}</td><td>{b.approved_days??0}</td><td>{b.pending_days??0}</td><td><strong>{b.remaining_days??0}</strong></td><td>{b.sick_leave_entitlement??0}</td><td>{b.sick_days_taken??0}</td><td><strong>{b.sick_days_remaining??0}</strong></td></tr>)}</tbody></table></div></section>
 <section className="section"><h2>Leave Requests</h2><div className="grid">{rows.length===0?<div className="card"><p>No team leave requests.</p></div>:rows.map(r=><div className="card" key={r.id}><span className="pill">{r.status}</span><h3>{r.employees?.first_name} {r.employees?.last_name}</h3><p><strong>{r.leave_type.replaceAll('_',' ')}</strong></p><p>{r.start_date} to {r.end_date}</p>{r.reason&&<p className="muted">{r.reason}</p>}{r.medical_certificate_path&&<p><button className="button secondary" type="button" disabled={openingCertificate===r.medical_certificate_path} onClick={()=>viewCertificate(r.medical_certificate_path!)}>{openingCertificate===r.medical_certificate_path?'Opening certificate...':'View medical certificate'}</button></p>}{r.manager_comment&&<p><strong>Comment:</strong> {r.manager_comment}</p>}{r.status==='pending'&&<div style={{display:'flex',gap:8}}><button className="button" onClick={()=>decide(r.id,'approved')}>Approve</button><button className="button" onClick={()=>decide(r.id,'declined')}>Decline</button></div>}</div>)}</div></section><section className="section"><Link href="/">← Back to My Portal</Link></section></main>;
}
